generated: '2025-09-12T06:31:50.557243Z'
galaxy:
  galaxy_id: ngc_628
  name: NGC 628
  aliases:
  - M 74
  ra_hms: 01 36 41.8
  dec_dms: +15 47 00.0
  morphology: SA(s)c
  distance_mpc: 7.3
  inclination_deg: 7
  position_angle_deg: 20
  extras:
  - 38.0
  - 0.08
  - 1.99
  - 218
