# """
# train_model.py
# ===============

# This script trains a lightweight U‑Net segmentation model to identify HI shells
# in moment maps.  It is designed to run efficiently on CPU‑only hardware such as
# an Apple M1 with limited memory.  Training and inference operate on tiles
# generated by ``data_processing.py``; each tile contains an intensity map and
# corresponding binary mask.

# Key features:

# * A simplified U‑Net architecture with three encoder–decoder stages and
#   reduced channel counts (default base number of filters is 32).  This
#   drastically reduces parameter count compared with standard U‑Nets while
#   retaining the skip connections necessary to capture multi‑scale context.
# * Combination of binary cross‑entropy (BCE) and Dice loss to balance
#   pixel‑wise classification and overlap metrics.  Dice loss mitigates
#   class‑imbalance by focusing on the relative intersection between predicted
#   and true masks.
# * Dataset class that reads NumPy ``.npz`` files generated by
#   ``data_processing.py``.  It normalizes the image values by subtracting the
#   median and dividing by the interquartile range (robust to outliers).
# * Training loop with progress logging, basic metric computation (precision,
#   recall, F1), and optional early stopping.

# Example usage:

#     python train_model.py --data_dir data/patches --epochs 25 --batch_size 4

# This will train the model and save the best performing weights (by Dice
# coefficient) to ``model_best.pth`` in the working directory.
# """

# from __future__ import annotations

# import argparse
# import os
# from pathlib import Path
# from typing import List, Tuple

# import numpy as np
# import torch
# import torch.nn as nn
# import torch.optim as optim
# from torch.utils.data import Dataset, DataLoader


# class TileDataset(Dataset):
#     """Dataset for loading tiles saved as NPZ files.

#     Each file produced by ``data_processing.py`` contains two arrays: ``image``
#     and ``mask``.  The dataset normalizes the image using robust statistics
#     (median and interquartile range) to reduce the impact of varying absolute
#     intensities between moment maps.
#     """

#     def __init__(self, file_list: List[Path]):
#         self.file_list = file_list

#     def __len__(self) -> int:
#         return len(self.file_list)

#     def __getitem__(self, idx: int) -> Tuple[torch.Tensor, torch.Tensor]:
#         path = self.file_list[idx]
#         with np.load(path) as npz:
#             img = npz['image'].astype(np.float32)
#             msk = npz['mask'].astype(np.float32)
#         # Robust normalisation: subtract median and divide by IQR
#         median = np.median(img)
#         q25, q75 = np.percentile(img, [25, 75])
#         iqr = q75 - q25
#         scale = iqr if iqr > 0 else 1.0
#         img = (img - median) / scale
#         # Expand dims for channel
#         img = np.expand_dims(img, axis=0)
#         msk = np.expand_dims(msk, axis=0)
#         return torch.from_numpy(img), torch.from_numpy(msk)


# class DoubleConv(nn.Module):
#     """A helper module: two consecutive convolutional layers with ReLU activation."""
#     def __init__(self, in_channels: int, out_channels: int):
#         super().__init__()
#         self.net = nn.Sequential(
#             nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1),
#             nn.BatchNorm2d(out_channels),
#             nn.ReLU(inplace=True),
#             nn.Conv2d(out_channels, out_channels, kernel_size=3, padding=1),
#             nn.BatchNorm2d(out_channels),
#             nn.ReLU(inplace=True),
#         )

#     def forward(self, x: torch.Tensor) -> torch.Tensor:
#         return self.net(x)


# class UNet(nn.Module):
#     """A lightweight U‑Net for binary segmentation."""
#     def __init__(self, in_channels: int = 1, base_channels: int = 32):
#         super().__init__()
#         # Encoder
#         self.enc1 = DoubleConv(in_channels, base_channels)
#         self.pool1 = nn.MaxPool2d(2)
#         self.enc2 = DoubleConv(base_channels, base_channels * 2)
#         self.pool2 = nn.MaxPool2d(2)
#         self.enc3 = DoubleConv(base_channels * 2, base_channels * 4)
#         self.pool3 = nn.MaxPool2d(2)
#         # Bottleneck
#         self.bottleneck = DoubleConv(base_channels * 4, base_channels * 8)
#         # Decoder
#         self.up3 = nn.ConvTranspose2d(base_channels * 8, base_channels * 4, kernel_size=2, stride=2)
#         self.dec3 = DoubleConv(base_channels * 8, base_channels * 4)
#         self.up2 = nn.ConvTranspose2d(base_channels * 4, base_channels * 2, kernel_size=2, stride=2)
#         self.dec2 = DoubleConv(base_channels * 4, base_channels * 2)
#         self.up1 = nn.ConvTranspose2d(base_channels * 2, base_channels, kernel_size=2, stride=2)
#         self.dec1 = DoubleConv(base_channels * 2, base_channels)
#         # Final output
#         self.final_conv = nn.Conv2d(base_channels, 1, kernel_size=1)

#     def forward(self, x: torch.Tensor) -> torch.Tensor:
#         # Encoder
#         x1 = self.enc1(x)
#         x2 = self.enc2(self.pool1(x1))
#         x3 = self.enc3(self.pool2(x2))
#         # Bottleneck
#         x4 = self.bottleneck(self.pool3(x3))
#         # Decoder
#         x = self.up3(x4)
#         x = torch.cat([x, x3], dim=1)
#         x = self.dec3(x)
#         x = self.up2(x)
#         x = torch.cat([x, x2], dim=1)
#         x = self.dec2(x)
#         x = self.up1(x)
#         x = torch.cat([x, x1], dim=1)
#         x = self.dec1(x)
#         x = self.final_conv(x)
#         return x


# def dice_loss(pred: torch.Tensor, target: torch.Tensor, smooth: float = 1.0) -> torch.Tensor:
#     """Compute the Dice loss for binary segmentation.

#     Dice loss is 1 - Dice coefficient.  The smooth term prevents division by
#     zero.
#     """
#     pred = torch.sigmoid(pred)
#     pred_flat = pred.view(pred.size(0), -1)
#     target_flat = target.view(target.size(0), -1)
#     intersection = (pred_flat * target_flat).sum(dim=1)
#     denom = pred_flat.sum(dim=1) + target_flat.sum(dim=1)
#     dice = (2.0 * intersection + smooth) / (denom + smooth)
#     return 1.0 - dice.mean()


# def compute_metrics(pred: torch.Tensor, target: torch.Tensor, threshold: float = 0.5) -> Tuple[float, float, float]:
#     """Compute precision, recall and F1 for a batch.

#     Parameters
#     ----------
#     pred : torch.Tensor
#         Raw model outputs (logits).
#     target : torch.Tensor
#         Ground truth binary masks.
#     threshold : float
#         Threshold applied to the sigmoid outputs to obtain binary predictions.

#     Returns
#     -------
#     precision : float
#     recall : float
#     f1 : float
#     """
#     with torch.no_grad():
#         probs = torch.sigmoid(pred)
#         pred_bin = (probs > threshold).float()
#         tp = (pred_bin * target).sum().item()
#         fp = (pred_bin * (1 - target)).sum().item()
#         fn = ((1 - pred_bin) * target).sum().item()
#         precision = tp / (tp + fp + 1e-8)
#         recall = tp / (tp + fn + 1e-8)
#         f1 = 2 * precision * recall / (precision + recall + 1e-8)
#     return precision, recall, f1


# def train(
#     model: nn.Module,
#     train_loader: DataLoader,
#     val_loader: DataLoader,
#     epochs: int = 20,
#     learning_rate: float = 1e-4,
#     weight_decay: float = 0.0,
#     device: str = 'cpu',
# ) -> nn.Module:
#     """Train the model and return the best performing model by Dice coefficient.

#     Parameters
#     ----------
#     model : nn.Module
#         U‑Net model to train.
#     train_loader : DataLoader
#         DataLoader for the training data.
#     val_loader : DataLoader
#         DataLoader for validation data.
#     epochs : int
#         Number of training epochs.
#     learning_rate : float
#         Initial learning rate for Adam optimiser.
#     weight_decay : float
#         L2 weight decay.
#     device : str
#         Device on which to perform training ('cpu' or 'cuda').

#     Returns
#     -------
#     model : nn.Module
#         The model with weights corresponding to the best validation Dice score.
#     """
#     model.to(device)
#     optimizer = optim.Adam(model.parameters(), lr=learning_rate, weight_decay=weight_decay)
#     bce = nn.BCEWithLogitsLoss()
#     best_dice = 0.0
#     best_state = None
#     for epoch in range(1, epochs + 1):
#         model.train()
#         total_loss = 0.0
#         for imgs, masks in train_loader:
#             imgs = imgs.to(device)
#             masks = masks.to(device)
#             optimizer.zero_grad()
#             outputs = model(imgs)
#             loss_bce = bce(outputs, masks)
#             loss_dice = dice_loss(outputs, masks)
#             loss = loss_bce + loss_dice
#             loss.backward()
#             optimizer.step()
#             total_loss += loss.item() * imgs.size(0)
#         avg_train_loss = total_loss / len(train_loader.dataset)
#         # Validation
#         model.eval()
#         val_loss = 0.0
#         dice_accum = 0.0
#         metrics_accum = np.zeros(3)
#         with torch.no_grad():
#             for imgs, masks in val_loader:
#                 imgs = imgs.to(device)
#                 masks = masks.to(device)
#                 outputs = model(imgs)
#                 val_loss += (bce(outputs, masks).item() + dice_loss(outputs, masks).item()) * imgs.size(0)
#                 # Dice coefficient
#                 dice_score = 1.0 - dice_loss(outputs, masks).item()
#                 dice_accum += dice_score * imgs.size(0)
#                 # Compute precision, recall, f1
#                 p, r, f1 = compute_metrics(outputs, masks)
#                 metrics_accum += np.array([p, r, f1]) * imgs.size(0)
#         avg_val_loss = val_loss / len(val_loader.dataset)
#         avg_dice = dice_accum / len(val_loader.dataset)
#         avg_metrics = metrics_accum / len(val_loader.dataset)
#         print(
#             f"Epoch {epoch}/{epochs} - "
#             f"Train loss: {avg_train_loss:.4f}, "
#             f"Val loss: {avg_val_loss:.4f}, Dice: {avg_dice:.4f}, "
#             f"Precision: {avg_metrics[0]:.3f}, Recall: {avg_metrics[1]:.3f}, F1: {avg_metrics[2]:.3f}"
#         )
#         # Save the best model
#         if avg_dice > best_dice:
#             best_dice = avg_dice
#             best_state = model.state_dict()
#     if best_state is not None:
#         model.load_state_dict(best_state)
#     return model


# def main() -> None:
#     parser = argparse.ArgumentParser(description="Train a lightweight U‑Net to detect HI shells.")
#     parser.add_argument(
#         "--data_dir",
#         required=True,
#         help="Directory containing training tiles (.npz files) generated by data_processing.py",
#     )
#     parser.add_argument(
#         "--val_split",
#         type=float,
#         default=0.2,
#         help="Fraction of data to use for validation",
#     )
#     parser.add_argument("--epochs", type=int, default=20, help="Number of training epochs")
#     parser.add_argument("--batch_size", type=int, default=4, help="Mini‑batch size")
#     parser.add_argument("--learning_rate", type=float, default=1e-4, help="Learning rate for Adam")
#     parser.add_argument("--base_channels", type=int, default=32, help="Number of base channels in U‑Net")
#     parser.add_argument(
#         "--device",
#         default="cpu",
#         choices=["cpu", "cuda"],
#         help="Device to train on",
#     )
#     args = parser.parse_args()

#     # List all NPZ files
#     data_dir = Path(args.data_dir)
#     files = sorted([p for p in data_dir.glob("*.npz")])
#     if not files:
#         raise FileNotFoundError(f"No .npz files found in {data_dir}")
#     # Shuffle and split
#     rng = np.random.default_rng(0)
#     indices = rng.permutation(len(files))
#     split = int(len(files) * (1.0 - args.val_split))
#     train_files = [files[i] for i in indices[:split]]
#     val_files = [files[i] for i in indices[split:]]
#     # Create datasets and loaders
#     train_ds = TileDataset(train_files)
#     val_ds = TileDataset(val_files)
#     train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True, num_workers=0)
#     val_loader = DataLoader(val_ds, batch_size=args.batch_size, shuffle=False, num_workers=0)
#     # Initialise model
#     model = UNet(in_channels=1, base_channels=args.base_channels)
#     # Train
#     model = train(
#         model,
#         train_loader=train_loader,
#         val_loader=val_loader,
#         epochs=args.epochs,
#         learning_rate=args.learning_rate,
#         device=args.device,
#     )
#     # Save the trained model
#     out_path = Path("model_best.pth")
#     torch.save(model.state_dict(), out_path)
#     print(f"Training complete.  Best model saved to {out_path}")


# if __name__ == "__main__":
#     main()

#!/usr/bin/env python3
# train_model.py — balanced U-Net training on filled masks (Apple M1 friendly)

#!/usr/bin/env python3
# train_model.py — robust, laptop-friendly training on FILLED masks (Apple M1 / CPU)


from __future__ import annotations
import argparse
from pathlib import Path
from typing import List, Tuple, Iterator
import math
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, Sampler

DEFAULT_DATA_DIR = "/Users/radish/Desktop/Tsinghua/HI Bubble Detection/patches_256s192"

# ---------------- Dataset ----------------
class TileDataset(Dataset):
    """Loads .npz tiles saved by data_processing.py. target ∈ {mask, region, rim}."""
    def __init__(self, files: List[Path], target: str = "mask"):
        self.files = files
        self.target = target

    def __len__(self) -> int:
        return len(self.files)

    def __getitem__(self, idx: int):
        p = self.files[idx]
        with np.load(p, allow_pickle=True) as z:
            img = z["image"].astype(np.float32)
            if self.target == "rim" and "rim" in z.files:
                m = z["rim"].astype(np.float32)
            else:
                key = "mask" if "mask" in z.files else ("region" if "region" in z.files else "rim")
                m = z[key].astype(np.float32)
        # robust per-tile normalize
        med = np.median(img)
        q25, q75 = np.percentile(img, [25, 75]); iqr = max(q75 - q25, 1e-6)
        img = (img - med) / iqr
        img = img[None, ...]  # C,H,W
        m = m[None, ...]
        return torch.from_numpy(img), torch.from_numpy(m)

# ---------------- Balanced sampler (50% pos / 50% neg per batch) ----------------
class BalancedBatchSampler(Sampler[List[int]]):
    def __init__(self, train_files: List[Path], labels: List[int], batch_size: int, pos_frac: float = 0.5, seed: int = 0):
        assert len(train_files) == len(labels)
        self.pos_idx = [i for i,l in enumerate(labels) if l == 1]
        self.neg_idx = [i for i,l in enumerate(labels) if l == 0]
        self.batch_size = batch_size
        self.k_pos = max(1, int(round(batch_size * pos_frac)))
        self.k_neg = batch_size - self.k_pos
        self.rng = np.random.default_rng(seed)
        # number of batches per epoch (with replacement sampling)
        base = max(len(self.pos_idx) / max(1, self.k_pos), len(self.neg_idx) / max(1, self.k_neg))
        self.num_batches = max(1, math.ceil(base))

    def __iter__(self) -> Iterator[List[int]]:
        for _ in range(self.num_batches):
            pos = self.rng.choice(self.pos_idx, size=self.k_pos, replace=True).tolist() if self.k_pos>0 else []
            neg = self.rng.choice(self.neg_idx, size=self.k_neg, replace=True).tolist() if self.k_neg>0 else []
            yield pos + neg

    def __len__(self) -> int:
        return self.num_batches

# ---------------- Model (GroupNorm for small batches) ----------------
def GN(ch: int) -> nn.GroupNorm:
    for g in (8, 4, 2, 1):
        if ch % g == 0:
            return nn.GroupNorm(g, ch)
    return nn.GroupNorm(1, ch)

class DoubleConv(nn.Module):
    def __init__(self, in_ch: int, out_ch: int):
        super().__init__()
        self.net = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, 3, padding=1), GN(out_ch), nn.ReLU(inplace=True),
            nn.Conv2d(out_ch, out_ch, 3, padding=1), GN(out_ch), nn.ReLU(inplace=True),
        )
    def forward(self, x): return self.net(x)

class UNet(nn.Module):
    def __init__(self, in_channels: int = 1, base_channels: int = 24):
        super().__init__()
        self.enc1 = DoubleConv(in_channels, base_channels); self.pool1 = nn.MaxPool2d(2)
        self.enc2 = DoubleConv(base_channels, base_channels*2); self.pool2 = nn.MaxPool2d(2)
        self.enc3 = DoubleConv(base_channels*2, base_channels*4); self.pool3 = nn.MaxPool2d(2)
        self.bottleneck = DoubleConv(base_channels*4, base_channels*8)
        self.up3 = nn.ConvTranspose2d(base_channels*8, base_channels*4, 2, 2); self.dec3 = DoubleConv(base_channels*8, base_channels*4)
        self.up2 = nn.ConvTranspose2d(base_channels*4, base_channels*2, 2, 2); self.dec2 = DoubleConv(base_channels*4, base_channels*2)
        self.up1 = nn.ConvTranspose2d(base_channels*2, base_channels, 2, 2);  self.dec1 = DoubleConv(base_channels*2, base_channels)
        self.final = nn.Conv2d(base_channels, 1, 1)
    def forward(self, x):
        x1 = self.enc1(x)
        x2 = self.enc2(self.pool1(x1))
        x3 = self.enc3(self.pool2(x2))
        x4 = self.bottleneck(self.pool3(x3))
        x  = self.up3(x4); x = torch.cat([x, x3], 1); x = self.dec3(x)
        x  = self.up2(x);  x = torch.cat([x, x2], 1); x = self.dec2(x)
        x  = self.up1(x);  x = torch.cat([x, x1], 1); x = self.dec1(x)
        return self.final(x)

# ---------------- Loss / metrics ----------------
def dice_loss(logits, target, smooth=1.0):
    prob = torch.sigmoid(logits)
    prob_f = prob.view(prob.size(0), -1)
    tgt_f  = target.view(target.size(0), -1)
    inter  = (prob_f * tgt_f).sum(1)
    denom  = prob_f.sum(1) + tgt_f.sum(1)
    dice = (2*inter + smooth) / (denom + smooth)
    return 1.0 - dice.mean()

def batch_metrics(logits, target, thr=0.2):
    with torch.no_grad():
        prob = torch.sigmoid(logits)
        pred = (prob > thr).float()
        tp = (pred * target).sum().item()
        fp = (pred * (1 - target)).sum().item()
        fn = ((1 - pred) * target).sum().item()
        prec = tp / (tp + fp + 1e-8)
        rec  = tp / (tp + fn + 1e-8)
        f1   = 2*prec*rec / (prec + rec + 1e-8)
    return prec, rec, f1

# ---------------- Split helpers ----------------
def autodetect_device(arg: str) -> str:
    if arg != "auto": return arg
    if torch.backends.mps.is_available(): return "mps"
    if torch.cuda.is_available(): return "cuda"
    return "cpu"

def stratified_files_and_labels(data_dir: Path, val_split: float) -> Tuple[List[Path], List[Path], List[int], List[int]]:
    files = sorted(data_dir.glob("*.npz"))
    if not files:
        raise FileNotFoundError(f"No .npz tiles in {data_dir}")
    idx_path = data_dir / "index.csv"
    if not idx_path.exists():
        rng = np.random.default_rng(0); perm = rng.permutation(len(files))
        cut = int(len(files)*(1.0 - val_split))
        # assume unknown labels → treat all negatives for sampler (we’ll fallback to shuffle)
        return [files[i] for i in perm[:cut]], [files[i] for i in perm[cut:]], [0]*cut, [0]*(len(files)-cut)
    df = pd.read_csv(idx_path)
    name_to_label = {Path(p).name: int(h) for p,h in zip(df["path"], df["has_pos"])}
    pos = [p for p in files if name_to_label.get(p.name, 0) == 1]
    neg = [p for p in files if name_to_label.get(p.name, 0) == 0]
    rng = np.random.default_rng(0); rng.shuffle(pos); rng.shuffle(neg)
    npos_val = max(1, int(len(pos)*val_split)); nneg_val = max(1, int(len(neg)*val_split))
    pos_val, pos_tr = pos[:npos_val], pos[npos_val:]
    neg_val, neg_tr = neg[:nneg_val], neg[nneg_val:]
    train_files = pos_tr + neg_tr; val_files = pos_val + neg_val
    rng.shuffle(train_files); rng.shuffle(val_files)
    # labels aligned to lists
    name_to_label_default0 = lambda p: name_to_label.get(p.name, 0)
    train_labels = [name_to_label_default0(p) for p in train_files]
    val_labels   = [name_to_label_default0(p) for p in val_files]
    print(f"[SPLIT] train: pos={sum(train_labels)} neg={len(train_labels)-sum(train_labels)} | val: pos={sum(val_labels)} neg={len(val_labels)-sum(val_labels)}")
    return train_files, val_files, train_labels, val_labels

# ---------------- Train ----------------
def train_loop(model, train_loader, val_loader, epochs, lr, wd, device, metric_thr, pos_weight):
    model.to(device)
    opt = optim.Adam(model.parameters(), lr=lr, weight_decay=wd)
    best_dice, best = 0.0, None

    for ep in range(1, epochs+1):
        model.train()
        tl = 0.0
        for x,y in train_loader:
            x,y = x.to(device), y.to(device)
            opt.zero_grad()
            out = model(x)
            bce = F.binary_cross_entropy_with_logits(out, y, pos_weight=torch.tensor(pos_weight, device=out.device))
            loss = 0.6*bce + 0.4*dice_loss(out, y)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
            opt.step()
            tl += loss.item()*x.size(0)
        tl /= len(train_loader.dataset)*1.0  # approximate when using custom sampler

        model.eval()
        vl = 0.0; dsum = 0.0; msum = np.zeros(3); pfrac = 0.0; N = 0
        with torch.no_grad():
            for x,y in val_loader:
                x,y = x.to(device), y.to(device)
                out = model(x)
                bce = F.binary_cross_entropy_with_logits(out, y, pos_weight=torch.tensor(pos_weight, device=out.device))
                val_loss = 0.6*bce + 0.4*dice_loss(out, y)
                bs = x.size(0); vl += val_loss.item() * bs; dsum += (1.0 - dice_loss(out, y).item()) * bs
                prec, rec, f1 = batch_metrics(out, y, thr=metric_thr); msum += np.array([prec, rec, f1]) * bs
                pfrac += y.mean().item() * bs; N += bs
        vl = vl / max(1,N); dice = dsum / max(1,N); prec, rec, f1 = (msum / max(1,N)); pfrac /= max(1,N)
        print(f"Epoch {ep:02d} | train {tl:.4f} | val {vl:.4f} | dice {dice:.4f} | P {prec:.3f} R {rec:.3f} F1 {f1:.3f} | val_pos_frac {pfrac:.5f}")

        if dice > best_dice:
            best_dice, best = dice, {k: v.cpu().clone() for k,v in model.state_dict().items()}

    if best is not None:
        model.load_state_dict(best)
    return model

# ---------------- Main ----------------
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--data_dir", default=DEFAULT_DATA_DIR)
    ap.add_argument("--val_split", type=float, default=0.2)
    ap.add_argument("--epochs", type=int, default=16)
    ap.add_argument("--batch_size", type=int, default=4)
    ap.add_argument("--learning_rate", type=float, default=1e-3)  # higher LR to escape zero solution
    ap.add_argument("--weight_decay", type=float, default=0.0)
    ap.add_argument("--base_channels", type=int, default=24)
    ap.add_argument("--target", choices=["mask","region","rim"], default="mask")
    ap.add_argument("--device", choices=["auto","cpu","cuda","mps"], default="auto")
    ap.add_argument("--metric_threshold", type=float, default=0.2)
    ap.add_argument("--pos_weight", type=float, default=5.0, help="fixed BCE pos_weight")
    ap.add_argument("--pos_frac_in_batch", type=float, default=0.5, help="target positive fraction per batch")
    args = ap.parse_args()

    device = autodetect_device(args.device)
    torch.set_num_threads(4)
    print(f"[INFO] device = {device}")

    data_dir = Path(args.data_dir)
    train_files, val_files, train_labels, val_labels = stratified_files_and_labels(data_dir, args.val_split)

    train_ds = TileDataset(train_files, target=args.target)
    val_ds   = TileDataset(val_files,   target=args.target)

    # Balanced batches (uses replacement; epoch length = ~max(pos/half, neg/half))
    sampler = BalancedBatchSampler(train_files, train_labels, batch_size=args.batch_size, pos_frac=args.pos_frac_in_batch, seed=0)
    train_ld = DataLoader(train_ds, batch_sampler=sampler, num_workers=0)
    val_ld   = DataLoader(val_ds,   batch_size=args.batch_size, shuffle=False, num_workers=0)

    model = UNet(in_channels=1, base_channels=args.base_channels)

    # small prior to avoid dead negatives
    with torch.no_grad():
        prior = 0.05
        model.final.bias.fill_(float(np.log(prior/(1.0-prior))))

    model = train_loop(model, train_ld, val_ld, args.epochs, args.learning_rate, args.weight_decay, device, args.metric_threshold, args.pos_weight)

    out = Path("model_best.pth")
    torch.save(model.state_dict(), out)
    print(f"[OK] saved → {out}")

if __name__ == "__main__":
    main()